# Generated by Django 6.0.3 on 2026-03-20 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_v6_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professoroccupiedtime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Assign to a department for priority scheduling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='scheduler.department'),
        ),
        migrations.AlterField(
            model_name='roomoccupiedtime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lab_room',
            field=models.ForeignKey(blank=True, help_text='Pin this lab/subject to a specific room (e.g. Python Lab → Lab 1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_subjects', to='scheduler.room'),
        ),
    ]
