# Generated by Django 6.0.3 on 2026-03-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_enhanced_csv_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professoroccupiedtime',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='professoroccupiedtime',
            name='end_slot',
            field=models.IntegerField(choices=[(1, '9:00–9:50'), (2, '9:50–10:40'), (3, '10:40–11:30'), (4, '11:30–12:20'), (5, '12:20–1:10'), (6, '2:00–2:50'), (7, '2:50–3:40')]),
        ),
        migrations.AlterField(
            model_name='professoroccupiedtime',
            name='is_quick_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professoroccupiedtime',
            name='start_slot',
            field=models.IntegerField(choices=[(1, '9:00–9:50'), (2, '9:50–10:40'), (3, '10:40–11:30'), (4, '11:30–12:20'), (5, '12:20–1:10'), (6, '2:00–2:50'), (7, '2:50–3:40')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='allowed_subjects',
            field=models.TextField(blank=True, default='all', help_text='"all" or comma-separated subject names/codes this lab can host.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='scheduler.department'),
        ),
        migrations.AlterField(
            model_name='roomoccupiedtime',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='roomoccupiedtime',
            name='end_slot',
            field=models.IntegerField(choices=[(1, '9:00–9:50'), (2, '9:50–10:40'), (3, '10:40–11:30'), (4, '11:30–12:20'), (5, '12:20–1:10'), (6, '2:00–2:50'), (7, '2:50–3:40')]),
        ),
        migrations.AlterField(
            model_name='roomoccupiedtime',
            name='start_slot',
            field=models.IntegerField(choices=[(1, '9:00–9:50'), (2, '9:50–10:40'), (3, '10:40–11:30'), (4, '11:30–12:20'), (5, '12:20–1:10'), (6, '2:00–2:50'), (7, '2:50–3:40')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='custom_section_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='custom_year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Subject Code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lab_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_subjects', to='scheduler.room'),
        ),
    ]
