# Generated by Django 6.0.5 on 2026-05-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_section_class_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentsettings',
            name='dept_start_slot',
            field=models.IntegerField(choices=[(1, '9:00–9:50'), (2, '9:50–10:40'), (3, '10:40–11:30'), (4, '11:30–12:20'), (5, '12:20–1:10'), (6, '1:10–2:00'), (7, '2:00–2:50'), (8, '2:50–3:40'), (9, '3:40–4:30')], default=1, help_text='First slot of the day for this department (default: 1 = 9:00 AM)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='group',
            field=models.CharField(choices=[('G1', 'Group 1'), ('G2', 'Group 2'), ('G3', 'Group 3'), ('G4', 'Group 4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='allowed_groups',
            field=models.CharField(choices=[('G1', 'Group 1 Only'), ('G2', 'Group 2 Only'), ('G3', 'Group 3 Only'), ('G4', 'Group 4 Only'), ('BOTH', 'All Groups')], default='BOTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot',
            field=models.IntegerField(),
        ),
    ]
