# Generated by Django 6.0.5 on 2026-05-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_add_g3_g4_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_start_slot',
            field=models.IntegerField(blank=True, choices=[(1, '9:00–9:50'), (2, '9:50–10:40'), (3, '10:40–11:30'), (4, '11:30–12:20'), (5, '12:20–1:10'), (6, '1:10–2:00'), (7, '2:00–2:50'), (8, '2:50–3:40'), (9, '3:40–4:30')], help_text='Override start time for this section (leave blank to use department default).', null=True),
        ),
    ]
