# Generated by Django 6.0.6 on 2026-06-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_add_section_start_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='scheduler.department'),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('DEPT_ADMIN', 'Department Admin')], default='DEPT_ADMIN', max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, help_text='Required for Department Admins; leave blank for full Admins.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='scheduler.department')),
            ],
        ),
    ]
