# Generated by Django 6.0.6 on 2026-06-10 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_professor_department_professor_professor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorFixedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, default='', max_length=100)),
                ('section_restriction', models.CharField(blank=True, default='', max_length=200)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('start_slot', models.IntegerField(choices=[(1, '9:00–9:50'), (2, '9:50–10:40'), (3, '10:40–11:30'), (4, '11:30–12:20'), (5, '12:20–1:10'), (6, '1:10–2:00'), (7, '2:00–2:50'), (8, '2:50–3:40'), (9, '3:40–4:30')])),
                ('end_slot', models.IntegerField(choices=[(1, '9:00–9:50'), (2, '9:50–10:40'), (3, '10:40–11:30'), (4, '11:30–12:20'), (5, '12:20–1:10'), (6, '1:10–2:00'), (7, '2:00–2:50'), (8, '2:50–3:40'), (9, '3:40–4:30')])),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_slots', to='scheduler.professor')),
            ],
        ),
    ]
