# Generated by Django 6.0.6 on 2026-06-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_professorfixedslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
