# Generated by Django 6.0.6 on 2026-06-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('CUSTOM', 'Custom')], max_length=10),
        ),
    ]
