# Generated by Django 6.0.6 on 2026-06-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_teachingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
