# Generated by Django 6.0.6 on 2026-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_teachingassignment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='program',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
