# Generated by Django 6.0.6 on 2026-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_section_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='shared_professors', to='scheduler.department'),
        ),
    ]
