# Generated by Django 6.0.6 on 2026-06-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_professor_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments', to='scheduler.department'),
        ),
    ]
