# Generated by Django 6.0.6 on 2026-06-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_teachingassignment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
